[package]
name = "xtask"
version = "0.15.4"
edition = "2021"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.48", features = ["derive", "string"] }
clap_complete = "4.5.58"
clap_mangen = "0.2.29"
regex = "1.11.3"
serde = "1.0.228"
serde_json = "1.0.145"
