[package]
name = "xtask"
version = "0.15.4"
edition = "2021"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.54", features = ["derive", "string"] }
clap_complete = "4.5.64"
clap_mangen = "0.2.31"
regex = "1.12.2"
serde = "1.0.228"
serde_json = "1.0.149"
